cli/command_test.go
cli/destroy_test.go
cli/query.go
cli/query_network_test.go
exec/os/bin/delaynetwork.go
exec/os/bin/lossnetwork.go
exec/os/network.go
exec/os/network_delay.go
exec/os/network_loss.go

refactor: modify device to interface in network experiment

---

exec/os/bin/burnio.go
exec/os/bin/filldisk.go
exec/os/disk.go
exec/os/disk_burn.go
exec/os/disk_fill.go
util/util_test.go

1. In order to better understand the meaning of the `--mount-point` flag, the parameter name in code was modified.
2. Add `--mount-point` value check to fix the issue #19

refactor: unify the disk experiment flag name and add value judgment

---

exec/kubernetes/spec_delete.go

When invoking destroy command for k8s delete experiment, blade will return success directly.
fix #29

bugfix: fix destroy experiment is delete k8s pod error

---

cli/prepare.go
cli/query_disk.go
exec/os/bin/dropnetwork.go
exec/os/bin/filldisk.go

and the wrong variable in network drop

fix the disk mount point querying

---

exec/jvm/sandbox.go

When executing `blade jvm prepare` command, the chaosblade-java-agent module is loaded twice.
Delete `refresh` operation in `sandbox.go` file.
See ~/logs/chaosblade/chaosblade.log

bugfix: fix java agent reloaded

---

exec/jvm/sandbox.go

see #77 details
Get `java` command path from JAVA_HOME env.

bugfix: fix the java bin path when preparing

---

cli/main.go
cli/query_jvm.go
exec/jvm/executor.go
exec/jvm/sandbox.go
util/util.go

Assert whether the java experiment is in effect and get the hit counts.
Feature #100 
1. Add `jvm` subcommand in `query` command.
2. Add `status` handler in chaos java agent.
Create a java experiment and execute `blade query jvm UID` command. Compare returned results and triggered times.
Modified the `util.Curl` function, added response code return value.

feature: add query for the hit counts of java experiments

---

cli/revoke.go

Fix java agent attach status error caused by revoke repeatly
see this #120 
check prepare record status, if it's already "Revoked", db record will not be changed to the wrong status and print success instead of fail.
see #120

fix status error caused by repeatly revoke

---

Makefile
cli/exp.go
cli/main.go
cli/prepare.go
cli/prepare_cplus.go
cli/prepare_jvm.go
cli/prepare_test.go
cli/revoke.go
exec/cplus/cplus.go
exec/cplus/executor.go
transport/response.go
util/util.go

feature: add support for cplus executor

---

cli/command_test.go
cli/prepare.go
cli/prepare_cplus.go
cli/prepare_jvm.go
cli/prepare_test.go
data/preparation.go
data/source.go
exec/cplus/executor.go
exec/jvm/executor.go
exec/jvm/sandbox.go
exec/local.go

See #132 for the detail.
1. Add pid column in chaosblade sqlite database. Identify database version by `PRAGMA user_version` and alter table if the target table version is old.
2. Add pid flag in preparation of jvm command.
3. Check the process by process name or pid value when executing jvm preparation. 
4. Record the pid value into sqlite.
5. Add pid flag support in chaosblade-exec-jvm project.
The process id of tomcat is 45399.
```
blade p jvm --process tomcat
{"code":200,"success":true,"result":"3abea82447412dc8"}
```
Use --pid argument, the blade will return the same uid:
```
blade p jvm --pid 45399
{"code":200,"success":true,"result":"3abea82447412dc8"}
```
1. The process and pid are not empty, then the process is used to find the process. If the process id and the found process are …

feature: add --pid for jvm preparation

---

exec/os/bin/burncpu/burncpu.go
exec/os/bin/burncpu/burncpu_test.go

Signed-off-by: youzhilane <youzhilane01@gmail.com>
Fixes #152 
modified the burncpu.go. when kill a pid run into an err then function stopBurnCpu return false and errsmsg.
```
$ sudo ./blade create cpu fullload --cpu-list=0-1
{"code":200,"success":true,"result":"e19ec23cb07c89ec"}
$ ./blade destroy e19ec23cb07c89ec               
{"code":604,"success":false,"error":"/bin/sh: 1: kill: Operation not permitted\n\n/bin/sh: 1: kill: Operation not permitted\n\n exit status 1 exit status 1"}
```

burnCpuStop return err fixed

---

util/util.go

make blade can be start any where if you use a relative path.
Fixes #48
use exec.LookPath and os.Readlink to get the execution path.

fix: Make blade can be start any where.

---

Makefile
cli/exp.go
exec/os/bin/burnmem/burnmem.go
exec/os/bin/burnmem/burnmem_test.go
exec/os/mem.go

In a Linux system, we can specify Memory usage of a machine by use command : blade c mem load --mem-percent value
#161 
Add multiple files using #tmpfs# file system to occupy memory
```
$ ./blade c mem load --mem-percent 50
{"code":200,"success":true,"result":"4ac2b3ad3f8c30bc"}
$ ./blade d 4ac2b3ad3f8c30bc
{"code":200,"success":true,"result":"command: mem load --debug false --help false --mem-percent 50"}
```

feature: specify Memory usage

---

exec/os/bin/filldisk/filldisk.go
exec/os/disk_fill.go
util/util.go

See #169 for details
Add `--path` flag to receive the directory where the disk occupied
`blade create disk fill --path /home/admin`
`blade create disk fill --path /`
We can specify any directory to fill disk.

Add path flag in disk fill to specify any directory

---

exec/os/bin/delaylossnetwork/delaylossnetwork.go
exec/os/bin/delaylossnetwork/delaylossnetwork_test.go
exec/os/network.go
exec/os/network_delay.go
exec/os/network_loss.go

#181 
1. Add `--destination-ip` flag
2. Add `match ip dst xxxx` command
`blade c network delay --time 3000 --interface eth0 --destination-ip 172.16.57.131 --local-port 8080`

feature: add destination ip flag

---

cli/exp.go

bugfix: add time unit description in timeout flag

---

exec/os/bin/delaylossnetwork/delaylossnetwork.go
exec/os/bin/delaylossnetwork/delaylossnetwork_test.go

#204 
The solution is to read the value of /sys/class/net/$device/tx_queue_len before executing the tc command. If it is greater than 0, it will not be processed. If the file is not found or is less than or equal to 0, execute ifconfig eth0 txqueuelen 1000. command.
Tested on linux4.9

bugfix: to be compatible with linux 4.9 about network

---

exec/docker/channel.go
exec/docker/spec.go

Signed-off-by: yixy <youzhilane01@gmail.com>
Provide capacity：Specify the repository when execute blade create docker
Fixes #222 
redefine `docker.NewDockerChannel()` by using global variable `docker.NewDockerChannelFunc`. As follows, it can specify the repository when execute blade create docker.
```
func NewDockerChannelUser(channel exec.Channel) (c *docker.Channel) {
c = &docker.Channel{}
c.Set(channel, fmt.Sprintf("%s:%s", "xxx", version.Ver))
return c
}
func main() {
docker.NewDockerChannelFunc = NewDockerChannelUser
baseCommand := cmd.CmdInit()
if err := baseCommand.CobraCmd().Execute(); err != nil {
_, _ = fmt.Fprintf(os.Stderr, "%s\n", err.Error())
os.Exit(1)
}
}
```

feature: Specify the repository when execute blade create docker

---

exec/jvm/executor.go
exec/jvm/sandbox.go

It solves the "too many process" error when calling ./blade prepare jvm --javaHome <javaPath> --process <process name> wich javaPath containing keyword "java"
e.g: ./blade prepare jvm --javaHome /home/q/java/default --process pf_noah_webapp, this should find only one pid by  process keyword "pf_noah_webapp", but right now it finds two pids by process keyword "pf_noah_webapp".
Fixes #288 
Use "blade" as keyword to exclude the false process when querying pids by process name.
After applying this fix, use example command "sudo ./blade prepare jvm --javaHome /home/q/java/default --process pf_noah_webapp" to verify, and the result should be like
{
"code": 200,
"success": true,
"result": "537cd831b5e7c613"
}

Bugfix solve too many process for prepare jvm with jave home

---

Makefile
build/image/musl/Dockerfile
go.mod
go.sum

See #298 
1. install maven in Dockerfile for compiling chaosblade-exec-jvm project
2. fix `build_with_linux` target. We can use the following command to compile linux version for the specify projects on mac, for example, compile chaosblade cli and chaosblade-exec-os projects:
```
ARGS="cli os" make build_with_linux
```
The `ARGS` values contain `cli`, `os`, `docker`, `kubernetes`, `java`, `cplus`
or use ` make build_linux` to compile all projects

bugfix: fix compile

---

Makefile
cli/cmd/command_test.go
cli/cmd/destroy.go
data/experiment.go
exec/jvm/sandbox.go
exec/kubernetes/executor.go
go.mod
go.sum

#336 
1. Add `--force-remove`, `--target` and `--kubeconfig` flags to destroy command, support to delete experiment record and chaosblade resource in k8s cluster.
2. Support to destroy chaosblade resources in k8s cluster if the experiment records do not exist.
Use kubectl to create chaosblade resource and destroy by blade command.
```
// Destroy experiments according to local records, including k8s experiments
blade destroy UID
// Destroy experiments according to the chaosblade resource name in the k8s cluster, it is applicable to the case that the local record does not exist.
blade destory UID --target k8s --kubeconfig KUBECONFIG
// Destroy and forcibly remove experiments according to local records, including k8s experiments
blade destroy UID …
```

feature: optimize chaosblade resource state flow in k8s experiments

---

cli/cmd/prepare_cplus.go
exec/cplus/cplus.go

The `chaosblade-exec-cplus` has been rewrited with golang, so modify the way of invoking the executor.
#380 
Delete unused flags about the c++ executor and replace jar file to executable binary file.
Execute the following command to test:
```
blade prepare cplus --port 8370
blade create cplus delay --delayDuration 10 --breakLine tcp_server.cpp:33 --fileLocateAndName /home/admin/cplustest/cplus/server/server --forkMode parent --processName /server --initParams 9527
blade destroy 1f3e9a9363a98471
blade revoke 46077401d6e22404
```

feature: apdat to the new cplus executor

---

cli/cmd/create.go

This PR is for issue #365 . This PR converts the timeout flag from a time interval `String` to a `Number`. It would be simpler for developers to give timeout as 2m ( 2 minutes ), 2m30s  than 120 and 90.
Fixes #365 
Regex module is used parsing the string and get Number. Two regular expressions are used.
1. To verify whether the time interval is in the correct format. [here](https://www.debuggex.com/r/rHj0N3qflvDVuz_L)
```^(\d+h)?(\d+m)?(\d+s)?$```
2. To form sub-strings for a timeout as Number. [here](https://www.debuggex.com/r/CPUCqkHD2JBuooCn)
```^(\d+h)?(\d+m)?(\d+s)?$```
Compile and test with `blade create cpu load --timeout 2m3s`
```sw4r4g@Acer-Avenger:/mnt/s/docker/test/chaosblade-0.6.0$ ./blade status a41bc92641c90a88
{
"code": 200,
"success": true,
"result": {
"Uid": …
```

feature: #365 upgraded timeout flag

---

exec/jvm/executor.go
exec/jvm/sandbox.go

when we use  chaosblade(chaosblade-exec-jvm) and jvm-sandbox-repeater same time,  there is a namespace conflict, which makes it unavailable. Because the default namespace of the two agents is "default", I want to modify the "default"namespace.
change chaosblade-exec-jvm default namespace from "default" to "chaosblade"

feature: change jvm sandbox default namespace

---

cli/cmd/exp.go
exec/jvm/executor.go
go.sum

chaosblade-io/chaosblade#524
Add the `refresh` flag judgement.
See chaosblade-io/chaosblade#189

feature: add refresh flag to support java agent reloading

---

exec/jvm/executor.go
exec/jvm/sandbox.go

chaosblade#551
Add `javaHome` in java experiments and parse it when creating.
```
blade c jvm cpufullload --javaHome /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home --process tomcat --refresh 
```

feature: support for specifing javaHome when creating java experiments

---

data/experiment.go

prepared statement should be closed explicitly, otherwise there will be a sqlite database lock problem

fix: prepared statement should be closed explicitly

---

data/preparation.go

fix #633 
1. Run Java the first Java application
2. Run Java The second Java application
3. Execute the command blade create jvm delay --time 4000 --classname=Test --methodname=add --pid pid1
3. Execute the command blade create jvm delay --time 4000 --classname=Test --methodname=add --pid pid2

fix: multiple Java process experiments use pid flag

---

exec/os/executor.go

Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
When the following statement is executed, the data in /tmp/abc will be truncated:
1. blade create file append --filepath=/tmp/abc --content="HELL WORLD"
2. in file /tmp/abc, there is only HELL in it, expected "HELL WORLD"
The cause of the problem is that strings.Split in chaosblade/exec/os/executor.go will truncate "HELL WORLD'" to "HELL" and "WORLD", that is, there are two data in argsArray, then chaosblade-exec- os will incorrectly parse --content as "HELL".
We need to make "HELL WORLD"  parse to one item in argsArray.
This bug will make the parsing of all parameters with spaces fail, such as filename, content, etc.
At the same time, I found that #46 has something to do with this bug. In chaos-exec-os, the uid failed to be resolved.
Fixes …

fix: Error passing arguments to chblade-exec-os.

---

data/experiment.go
data/preparation.go

Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
A useless for loop
Replace for with if.

fix: Eliminate useless for loops.

---

Makefile

musl-gcc is used when building nsexec in the Makefile, which uses absolute paths when executing, which is unnecessary. And doing so will fail to execute under some distributions. For example, in the[ PKGBUILD file of archLinux](https://github.com/archlinux/svntogit-community/blob/master/musl/repos/community-x86_64/PKGBUILD), /usr/bin/ is used as the storage path for executable files instead of /usr/local/.
NONE
I changed the execution absolute path of musl-gcc to look for execution in $PATH.
Just make directly.

fix: Modify the absolute path execution of musl-gcc

---

docs/beginner_guide_CN.md
docs/beginner_guide_EN.md
docs/chaos_experiment_model_CN.md
docs/chaos_experiment_model_EN.md
docs/logic_flow_Introduction_CN.md
docs/logic_flow_Introduction_EN.md

Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
The fact that chaosblade lacks adequate English documentation is a huge problem, and I've seen criticism of this problem in more than one article. 
1. https://harness.io/blog/devops/chaos-engineering-tools/
2. https://www.gremlin.com/community/tutorials/chaos-engineering-tools-comparison/#chaosblade
3. ...
So I tried to translate the existing Chinese documentation, as well as start working on the implementation of the command documentation (described in another ISSUE), which will be a long process.
The biggest advantage of chaosblade over other chaos engineering tools is its simplicity and ease of use, but the lack of adequate documentation is a matter of putting the cart before the horse.

docs: Add english documents.

---

cli/cmd/prepare_cplus.go

Signed-off-by: yangli <798862514@qq.com>
repair the prepare cplus process name from the original port number to the real process name.
NONE
replace the original port number with the process name
View the table preparation field process
NONE

Fix prepare cplus process name

---

Dockerfile
build/image/arm/Dockerfile
build/image/musl/Dockerfile
go.mod

update mod to 1.20

---

Makefile

It would be beneficial to make `/usr/local/musl/bin/musl-gcc` configurable, as it is often not available on developer's MacBooks, allowing users to adjust it according to their needs.
NONE
Introduce a variable CC for rule `nsexecgo ` in the makefile.

feat: Make musl-gcc configurable var to boost local builds

---

cli/cmd/exp.go

Delete redundant package import.

Delete redundant package import.

---

cli/cmd/cli.go
cli/cmd/cli_test.go
cli/cmd/prepare_jvm_test.go
cli/cmd/query_disk_test.go
cli/cmd/query_network_test.go
cli/cmd/status.go

- replaced "golang.org/x/crypto/ssh/terminal" with "golang.org/x/term"

refectoring: replacing deprecated packages

---

cli/cmd/check_java.go

- Replaced errors.New(fmt.Sprintf()) with fmt.Errorf(). According to the following blog, fmt.Errorf() is recommended for errors that require formatting, and errors.New() is recommended if the error text cannot be changed. ref: https://www.digitalocean.com/community/tutorials/how-to-add-extra-information-to-errors-in-go

refectroign: Error return function modification

---

Dockerfile

- Changed the apt source in the Dockerfile from deb.debian.org to mirrors.163.com.
- Updated the sed command to target the /etc/apt/sources.list.d/debian.sources file instead of the default /etc/apt/sources.list.
- This change ensures that the Docker image uses a faster and more reliable mirror for package downloads.

fix: update apt source to mirrors.163.com in debian.sources

---

nsexec.c

Fix #1146 
1. Add `/bin` to PATH.
2. Optimize error handling.
```
./blade c cri mem load --container-id 0cc6f9f157b182e1ed9a1a7b5110f8760bc2882dc203dc627313aee522e68eba --container-runtime containerd --mem-percent 80 --mode cache -d
{"code":200,"success":true,"result":"7542c2e8a6a0ae05"}
```
The log:
```
time="2025-09-10 15:18:02.282408363 CST" level=info msg="mode: create, target: mem, action: load, flags map[avoid-being-killed: cgroup-root:/sys/fs/cgroup channel:nsexec debug:true include-buffer-cache: mem-percent:80 mode:cache ns_mnt:true ns_net:false ns_pid:true ns_target:2023202 rate: reserve: uid:7542c2e8a6a0ae05]" location="/Users/changjun/Codespace/ChaosBladeProjects/chaosblade/target/cache/chaosblade-exec-os/main.go:123" uid=7542c2e8a6a0ae05
time="2025-09-10 15:18:02.282489071 …
```

Bugfix: Solve the problem of command failure in container scenario

---

data/preparation.go
data/source.go

Fix #1108 
Added column existence check: In the CheckAndInitPreTable() function, a check is added to check whether the pid column exists.
Implemented the ColumnExists method: Added the ColumnExists method in source.go to check whether a column exists in a specified table.
Optimized the migration logic: ALTER TABLE statements are executed only if the column does not exist.

fix: duplicate column name pid

---

cli/cmd/destroy.go
cli/cmd/query_k8s.go
exec/kubernetes/executor.go
exec/kubernetes/spec.go
version/version_info.go

#1184 
New parameters: `--kubectl-proxy` and `--token`.
If both --kubectl-proxy and --token are provided: token authentication is used directly, without relying on kubeconfig.
If both --kubectl-proxy and --kubeconfig are provided: authentication information is obtained from the kubeconfig file, and then access is performed through a proxy.
If only --kubectl-proxy is provided: authentication information is attempted from the default kubeconfig location, and if that fails, a simple proxy configuration is used.
Use case:
```
./blade c k8s pod-file append --filepath /opt/l.log --content "hello" --names chaosblade-tool-rw4kn --namespace chaosblade --kubectl-proxy "https://cloudshell.a-workbench.com:80"  --token xxxx 
```
```
1 root      0:00 kubectl --port 8080 proxy --server …
```

feat: Supports accessing the cluster through kubectl-proxy

---

data/source.go
data/source_test.go
go.mod
go.sum

Resolves #1039 
Added the getDataFilePath() function:
Preferentially reads the path from the CHAOSBLADE_DATAFILE_PATH environment variable.
If the environment variable is not set, the existing logic (util.GetProgramPath() + dataFile) is used.
If the path specified by the environment variable exists and is a directory, dataFile is placed in that directory.
If the path specified by the environment variable exists and is a file, the file path is used directly.
If the path specified by the environment variable does not exist, it is treated as a directory and the directory is automatically created.
```
ChaosBlade Version Information:
==============================
Version:     1.8.0
Git Tag:     v1.7.5
Git Commit:  95e1799
Git Branch:  feature-1039
Build Time:  Fri Sep 19 14:41:09 CST 2025 …
```

feat: Support specifying chaosblade data file path
