chaosblade-io/chaosblade

- exec/os/cpu.go
fix --numcpu parameter strong check
#44
> bugfix: fix --numcpu parameter strong check

- Makefile
- cli/exp.go
- exec/os/script.go
- exec/os/script_delay.go
- exec/os/script_exit.go
- transport/response.go
To inject a delay or an error code into a function in a specified script.
feature #59 
Find the `offline` function in `appctl.sh` file through the `awk '/offline\s?\(\)\s*\{/{print NR}' appctl.sh` and then add `sleep` or `exit` on the next line using `sed` command.
> feature: add script file chaos experiment

- exec/kubernetes/spec_delete.go
Delete multiple pods at the same time.
feature #51 
Add `--pods` flag multiple pod names separated by commas. for example, `blade c k8s delete --pods redis-slave-57f9f8db74-kx5x9,redis-slave-57f9f8db74-7h4q7
`
> feature: add --pods flag for deleting multiple pods

- CONTRIBUTING.md
Improves the Quality of documentation.
Fixes #90
> docs: fix typo and grammatical errors in CONTRIBUTING.md

- README.md
This PR fixed typos and grammatical errors in README.md file.
Yes, The fixed issue is #93 
Checked the Readme for typos and grammatical errors.
> docs: Fix typo and grammatical errors in README.md

- cli/prepare_jvm.go
- exec/jvm/sandbox.go
feature: prepare jvm add javaHome args
> feature: prepare jvm add javaHome args

- exec/jvm/executor.go
- exec/jvm/executor_test.go
"jvm return value" command do not support space or other invalid url char in value string
> Fixed #97 urlencode参数

- CONTRIBUTING.md
Signed-off-by: Enming.Zhang <zvampirem77@gmail.com>
Complete the missing parentheses in CONTRIBUTING.md
NONE
Complete the missing parentheses in CONTRIBUTING.md
NONE
NONE
> docs: completing the missing parentheses in CONTRIBUTING.md

- .travis.yml
- Makefile
- exec/kubernetes/channel_test.go
- exec/os/bin/burncpu/burncpu.go
- exec/os/bin/burnio/burnio.go
- exec/os/bin/changedns/changedns.go
- exec/os/bin/common.go
- exec/os/bin/delaynetwork/delaynetwork.go
- exec/os/bin/dropnetwork/dropnetwork.go
- exec/os/bin/filldisk/filldisk.go
- exec/os/bin/killprocess/killprocess.go
- exec/os/bin/lossnetwork/lossnetwork.go
Support travis CI
Create a .travis.yml file in the root directory
As long as the code changes, travis will automatically run the build and test and feedback the results
Because one main package can only have one main function, I adjusted the file structure
_from:_
exec/os/bin/
&nbsp;&nbsp;&nbsp;burncpu.go
&nbsp;&nbsp;&nbsp;burnio.go
&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;common.go
_to:_
exec/os/bin/
&nbsp;&nbsp;&nbsp;burncpu/burncpu.go
&nbsp;&nbsp;&nbsp;burnio/burnio.go
&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;common.go
> feature: add travis CI service

- .travis.yml
- Makefile
- README.md
- README_CN.md
- exec/kubernetes/channel_test.go
- exec/kubernetes/spec_test.go
- exec/local.go
- exec/local_mock.go
- exec/local_test.go
- exec/os/bin/burncpu/burncpu.go
- exec/os/bin/burncpu/burncpu_test.go
- exec/os/bin/burnio/burnio.go
- exec/os/bin/burnio/burnio_test.go
- exec/os/bin/changedns/changedns.go
- exec/os/bin/changedns/changedns_test.go
- exec/os/bin/common.go
- exec/os/bin/delaynetwork/delaynetwork.go
- exec/os/bin/delaynetwork/delaynetwork_test.go
- exec/os/bin/dropnetwork/dropnetwork.go
- exec/os/bin/dropnetwork/dropnetwork_test.go
- exec/os/bin/filldisk/filldisk.go
- exec/os/bin/filldisk/filldisk_test.go
- exec/os/bin/killprocess/killProcess_test.go
- exec/os/bin/killprocess/killprocess.go
- exec/os/bin/lossnetwork/lossnetwork.go
- exec/os/bin/lossnetwork/lossnetwork_test.go
- exec/os/cpu_test.go
- go.mod
- transport/response.go
1. add some test files
2. add test option to Makefile to use command _make test_
3. integrated test coverage tool [codecov](https://codecov.io)
4. add some badges to README.md and README_CN.md to show test coverage of the project
> 3. integrated test coverage tool [codecov](https://codecov.io)
To start codecov service, you should go to [codecov](https://codecov.io), login, login with github, and add repository chaosblade.
>  test: add some test files

- Makefile
- exec/local.go
- exec/os/bin/killprocess/killprocess.go
- exec/os/bin/stopprocess/stopprocess.go
- exec/os/process.go
- exec/os/process_kill.go
- exec/os/process_stop.go
Process fake death is a problem that always happen.
Reconstruct process module and add this feature
`./blade c process stop --process xx`
> feature: make process fake death, this scene can be destroy

- cli/prepare_jvm.go
- cli/revoke.go
- exec/jvm/sandbox.go
See #138 for details
1. add --port, -P flag to specify the agent port, the flag is unnecessary.
2. check response returns when attaching failed and print the solution tips.
`blade prepare jvm --process xxx --port 8703`
> feature: add --port args for jvm preparation

- exec/os/bin/filldisk/filldisk.go
call `fallocate` to fill disk space without realy io, when the environment filesystem is common linux filesystem(ext4, xfs, btrfs and ocfs2 etc.)
see #143
> feature: add quick works support for disk fill 

- exec/os/bin/stopprocess/stopprocess.go
https://github.com/chaosblade-io/chaosblade/issues/167
yes ,see https://github.com/chaosblade-io/chaosblade/issues/167
repalced by kill -STOP pid、kill – CONT pid
i hava tested in mac and linux
> fix:stop process repalced by kill -STOP –CONT

- cli/command_test.go
- cli/prepare.go
- cli/prepare_jvm.go
- data/preparation.go
- exec/jvm/sandbox.go
- exec/local.go
- util/util.go
#178 
Add `sudo -u USER` when prepare
> bugfix: fix unable to access sandbox-core.jar

- exec/local.go
> bugfix: fix chaosblade dir contains blank space

- cli/cmd/cli.go
- cli/cmd/cli_test.go
- cli/cmd/cmd.go
- cli/cmd/command.go
- cli/cmd/command_test.go
- cli/cmd/create.go
- cli/cmd/destroy.go
- cli/cmd/destroy_test.go
- cli/cmd/exp.go
- cli/cmd/prepare.go
- cli/cmd/prepare_cplus.go
- cli/cmd/prepare_jvm.go
- cli/cmd/prepare_jvm_test.go
- cli/cmd/prepare_test.go
- cli/cmd/query.go
- cli/cmd/query_disk.go
- cli/cmd/query_disk_test.go
- cli/cmd/query_jvm.go
- cli/cmd/query_network.go
- cli/cmd/query_network_test.go
- cli/cmd/revoke.go
- cli/cmd/status.go
- cli/cmd/version.go
- cli/main.go
Signed-off-by: yixy <youzhilane01@gmail.com>
I tried to adjust the cli directory structure
Fixes #189
> feature: adjust the cli directory structure

- exec/cplus/cplus.go
- exec/os/bin/burnio/burnio.go
- exec/os/bin/burnio/burnio_test.go
- exec/os/disk_burn.go
- go.sum
- util/log.go
#82 #195 #194 
1. Use `path` flag to replace `mount-point` flag, you can use `--path` to specify any directory.
2. For less configuration, `count` flag was deleted.
`blade c disk burn --read --path /home/admin`
`blade c disk burn --write --path /home/admin`
`blade c disk burn --read --write --path /home/admin`
`blade c disk burn --read --write --path /home/admin --timeout 30`
> feature: enhance the disk burn experiments

- Makefile
- cli/cmd/version.go
- exec/docker/channel.go
- version/version.go
#197 
Change `importpath` in Makefile.
`blade version`
> bugfix: fix blade version

- Makefile
#202 
delete build cpu burn for linux in Makefile
run in docker container
> bugfix: change cpu burn for linux

- Dockerfile
update golang to 1.13.4 and alpine to 3.10.3 in dockerfile
Altered images used in from statements of dockerfile
> bump golang to 1.13.4 and alpine to 3.10.3

- cli/cmd/server_start.go
#246 
Add `ip` flag in `blade server start` command.
`blade server start --ip 127.0.0.1`
`blade server start --ip 192.168.1.1`
`blade server start`
> feature: add ip setting for blade server command

- cli/cmd/command.go
- cli/cmd/command_test.go
- cli/cmd/create.go
- cli/cmd/destroy.go
- cli/cmd/prepare.go
- cli/cmd/prepare_cplus.go
- cli/cmd/prepare_test.go
- cli/cmd/revoke.go
- cli/cmd/status.go
- data/experiment.go
- data/preparation.go
- data/source.go
> feature: add status and limit flag in status command

- exec/jvm/executor.go
- go.mod
- go.sum
#266 
Add post request function in chaosblade-spec-go project and change to post when invoking sandbox.
> feature: change create request method to post for java experiments

- exec/cplus/executor.go
- exec/jvm/executor.go
- go.mod
- go.sum
#271 
1. Fix the err variable scope.
2. Handle the unmarshal json result.
> bugfix: fix error handled about creating java and cplus experiments

- Makefile
add git alert message when version older then 1.8.5
Fixes #279 
add a checkpoint when git version is illegal
> Update Makefile: add git alert message when version older then 1.8.5

- cli/cmd/cmd.go
- cli/cmd/server_status.go
新增子命令 `server status`，主要用于部署到k8s上之后进行健康检查
检测 server 进程以及运行端口
检查 server 进程是否存在，若存在则返回 up 状态以及 server 的端口号
> add cli command server status

- go.mod
- go.sum
Signed-off-by: yixy <youzhilane01@gmail.com>
Fixes #296
> bugfix:fix os exp dependencies

- README.md
- README_CN.md
fix typo in readme and readme_CN
fix issue : #309
> docs: fix typo in README_CN.md and README.md

- README.md
- README_CN.md
This reverts commit 476035b144a42869d926bc05b8b9d08408254525.
> Revert "docs: fix typo in README_CN.md and README.md (#311)"

- Dockerfile
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
Updated 
Updated OS and software used to docker image to resolve security issues
> Updated to Golang 1.14.0, MUSL 1.2.0 and Alpine 3.10.4

- cli/cmd/destroy.go
- cli/cmd/server_stop.go
- go.mod
- go.sum
Fix error message output format problem in server mode.
#321 
Determine the result of the Destroy command, if successful, use cmd api output, if not, directly return the error message.
Execute correct and incorrect commands respectively.
> bugfix: fix output message for server mode

- exec/jvm/sandbox.go
- exec/jvm/sandbox_test.go
- go.mod
- go.sum
#327 
Fix error codes.
Add unit test
> bugfix: fix tools.jar path finding for java experiments

- Makefile
- go.mod
- go.sum
#331 
Add `-X ${DOCKER_BLADE_VERSION}.BladeVersion=$(BLADE_VERSION)` to specify chaosblade version for docker.
Create docker experiments to test.
> feature: support to specify chaosblade version for docker experiments

- cli/cmd/command_test.go
- cli/cmd/destroy.go
- cli/cmd/status.go
- data/experiment.go
- go.mod
- go.sum
#334 
Support destroy command without uid to modify experiment status.
> bugfix: fix cannot get output about docker experiments

- build/spec/chaosblade.spec.yaml
> add exclude-ip

- .travis.yml
- Makefile
- build/image/blade/Dockerfile
- build/image/musl/Dockerfile
Fix build error, when compile with build_with_linux argument in macos.
Fixes #359
1. add mirror to dockerfile
2. add volume to build_with target in the make file
> fixed build_with_linux on the macos

- exec/kubernetes/executor.go
#370 
Add TypeMeta data to resource.
Execute the following command to test:
```
blade d cf42ad21efbd2f20 --target k8s --force-remove --kubeconfig ~/.kube/config
```
> bugfix: fix forcibly delete error bug

- Makefile
- cli/cmd/command_test.go
- cli/cmd/server_status.go
- exec/jvm/sandbox.go
- exec/jvm/sandbox_test.go
- go.mod
- go.sum
#319 
Use gopsutil lib to replace ps command.
Compile and test.
> Replace ps command to gopsutil

- Makefile
- build/image/musl/Dockerfile
Signed-off-by: tiny.x 185120555@qq.com
#408 
Slim down the blade executable file
- use upx
- -ldflags "-s -w"
> feature: slim down the blade toolkit

- README.md
> feature:improvement README.md

- Makefile
- build/image/arm/Dockerfile
- build/image/upx/Dockerfile
improvement compile, add usage
java scenario does not need to be compiled separately
#419 
add usage
make
> feature:improvement compile, add usage

- cli/cmd/create.go
https://github.com/chaosblade-io/chaosblade-operator/issues/34
> fixbug: use --timeout flag in k8s environment

- build/image/blade/Dockerfile
fixbug: `blade create k8s node-disk burn` error
Fixes #375 
chaosblade-tool install `coreutils` lib
````
blade create k8s node-disk burn --read --names izbp1a4jchbdwkwi5hk7ekz --kubeconfig ~/.kube/config
````
> fixbug: `blade create k8s node-disk burn` error

- exec/jvm/executor.go
Destroy java experiment by action
#431 
````
blade p jvm -p Provider
rm -f chaosblade.dat
blade destroy jvm cpufullload --process Provider
````
> fixbug:Destroy java experiment by action

- exec/jvm/executor.go
#439 
Process or PID is not specified
````
blade create jedis delay --time 3000 --key tank_hello
````
````
blade destroy jedis delay
````
> fixbug: blade destroy fail

- Makefile
- build/image/blade_arm/Dockerfile
#438
use multiarch/alpine:arm64-edge image
`make build_image_arm`
> feature: Support for build ARM chaosblade-tool images

- Makefile
- exec/jvm/executor.go
> fix: if jvm restart run experiment error

- Makefile
- exec/os/executor.go
- go.mod
feature:
- Separate cli and exec-os
> feature: Separate cli and exec-os

- exec/os/executor.go
Signed-off-by: tiny-x <xf.yefei@gmail.com>
> fix: ssh execution channel does not take effect

- cli/cmd/create.go
Add scope value judgment and make command combination.
Compile and test it.
> bugfix: fix asynchronous experiment creation

- cli/cmd/check_os.go
Add code assignment code.
Compile and test it.
> bugfix: fix the return code of the check result under ok condition

- exec/jvm/sandbox.go
Fix the impact of JAVA_TOOL_OPTIONS parameter on loading java agent.
Set `JAVA_TOOL_OPTIONS` env to empty for the current shell.
> bugfix: exclude the influence of JAVA_TOOL_OPTIONS variable

- cli/cmd/create.go
- exec/jvm/executor.go
Execute error when using async parameter
Handle the case of direct return from asynchronous execution.
> bugfix: fix creating with async flag

- README.md
- README_CN.md
Add AUR Package
Add AUR Package
> Add AUR Package

- cli/cmd/check_os.go
find a typo.
#651
just modify it.
> fix: fix a typo in check_os.go

- cli/cmd/create.go
Signed-off-by: NigelWu95 <bingheng.wbh@antgroup.com>
> fix: action flag bind default value from spec.ExpFlagSpec

- cli/cmd/create.go
Signed-off-by: tiny-x <xf.yefei@gmail.com>
fix: ssh exec.
https://github.com/chaosblade-io/chaosblade/issues/755
> fix: ssh exec.

- Makefile
- build/spec/spec.go
- cli/cmd/exp.go
- exec/kubernetes/executor_compose.go
Signed-off-by: caimingxia <mingshao.cmx@alibaba-inc.com>
> fix spec to build chaosblade.spec.yaml

- exec/jvm/sandbox.go
Fixes missing parameter bug
Fixes #939
> fix: add err parameter for log.Warnf

- Makefile
At present, there are errors in the compiled arm64 image. We have submitted this compilation method after testing, so we fix the problems in the compilation of arm architecture.
use buildx .
> Fix problems in arm64 compilation

- cli/cmd/cmd.go
- cli/cmd/server_start.go
> fix: Temporarily disable server mode.

- Makefile
Image tags in makefile are wrong.
NONE.
Replace all chaosbladeio with chaosblade-io of image tags.
> fix: wrong image tag

- build/spec/spec.go
Fix chaosblade version in spec
> Fix chaosblade version in spec

- data/preparation.go
/kind bug
Fix bug of preparation db index .
> Fix bug of preparation db index .

- build/image/blade/Dockerfile
- build/image/musl/Dockerfile
- build/image/upx/Dockerfile
> fix: upgrade deprecated image tag

- cli/cmd/check_os.go
Simplify append code in for loop
> refectoring: Simplify append code in for loop

- cli/cmd/check_java.go
- cli/cmd/check_os.go
- cli/cmd/create.go
- cli/cmd/server_stop.go
- cli/cmd/status.go
> refectoring: Delete unnecessary code

- MAINTAINERS.md
> chore: update and reformat MAINTAINERS.md
